% Author: Suvadip Mukherjee
% This script is used to downscale the original ground truth swc file to
% the desired dimension. This is necessary to do comparison between the swc

% DOWNSCALESWC 

fprintf('\n Get the actual Image');
origImg = read3DStack(1,1);

fprintf('\n Get the subsampled Image');
scaledImg = read3DStack(1,1);

%%
downscale = 1;
if downscale
    [actY actX actD] = size(origImg);
    [finY finX finD] = size(scaledImg);
    
else
    [finY finX finD] = size(origImg);
    [actY actX actD] = size(scaledImg);
end

%%

origSWC_fname = uigetfile('./*.swc','Input ground truth .swc file');

fid = fopen(origSWC_fname);
if (fid == -1)
    fprintf('File = %s Not found\n',fileName);
    coordSwc = -1 ;
    return;
end

origSWC = readSWC(origSWC_fname);


origSWC = origSWC' ;

%%
radiiRatio = sqrt(finX^2+finY^2+finD^2)/sqrt(actX^2+actY^2+actD^2);

scaledSWC = zeros(size(origSWC));

scaledX = scaledSWC(:,3); origX = origSWC(:,3);
scaledY = scaledSWC(:,4); origY = origSWC(:,4);
scaledZ = scaledSWC(:,5); origZ = origSWC(:,5);
scaledR = scaledSWC(:,6); origR = origSWC(:,6);

scaledX = 1+(origX-1)*(finX-1)/(actX-1);
scaledY = 1+(origY-1)*(finY-1)/(actY-1);
scaledZ = 1+(origZ-1)*(finD-1)/(actD-1);
scaledR = radiiRatio*origR;

scaledSWC(:,3) = (scaledX);
scaledSWC(:,4) = (scaledY);
scaledSWC(:,5) = (scaledZ);
scaledSWC(:,6) = scaledR;
scaledSWC(:,1) = origSWC(:,1);
scaledSWC(:,2) = origSWC(:,2);
scaledSWC(:,7) = origSWC(:,7);

%% Write the new swc file

newname = [origSWC_fname '_scaled.SWC'];
fp = fopen(newname,'w+');

line1 = '# New Subsampled groundtruth generated by Suvadip' ;
fprintf(fp,line1);
fprintf(fp,'\n');
length = size(scaledSWC,1);
for i = 1 : length
    toPrint = num2str(scaledSWC(i,:));
fprintf(fp,'%s\n',toPrint);
end
fclose(fp);

fprintf('\n Done');